format_version: 9

pipelines:
  build-maps:
    group: Map-Creation-Group
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      mappipelines:
        type: configrepo
        destination: configyaml
    stages:
      - stage-run-map-create:
          jobs:
            job-run-map-create:
              resources:
                - arcmap10-6
              artifacts:
                - build:
                    source: GIS/3_Mapping/34_Map_Products_MapAction
                    destination: maps
              tasks:
                - exec:
                    command: cmd
                    arguments:
                      - "/c"
                      - "C:/py27arcgis106/ArcGIS10.6/python.exe"
                      - "-m"
                      - virtualenv
                      - "--system-site-packages"
                      - env
                - exec:
                    command: cmd
                    arguments:
                      - "/c"
                      - "./env/Scripts/python.exe"
                      - "-m"
                      - pip
                      - install
                      - mapactionpy-controller
                - exec:
                    command: cmd
                    arguments:
                      - "/c"
                      - "./env/Scripts/python.exe"
                      - "-m"
                      - pip
                      - install
                      - mapactionpy-arcmap
                - exec:
                    command: cmd
                    arguments:
                      - "/c"
                      - "./env/Scripts/python.exe" 
                      - "-m"
                      - mapactionpy_controller.check_naming_convention
                      - "%pipeline_cmf_description_path%"
                - exec:
                    command: cmd
                    arguments:
                      - "/c"
                      - "./env/Scripts/python.exe" 
                      - "-m"
                      - mapactionpy_arcmap.arcmap_runner 
                      - "--cmf"
                      - "%pipeline_event_description_path%"
                      - "--product"
                      - "Country Overview with Admin 1 Boundaries & P-Codes"
                  