format_version: 9
common:
  task_venv: &task_launch
    - exec:
        command: cmd
        arguments:
          - "/c"
          - echo
          - "%MAPCHEF_EVENT_DESC%"

pipelines:
  sri-lanka:
    group: Per-Country-Map-Creation
    display_order: -10    
    environment_variables:
      MAPCHEF_EVENT_DESC: "\\\\192.168.106.24\\Non-Mission\\development\\data_circle\\metis\\output-test-suite\\2019lka01\\event_description.json"
      # event_desc: "\\\\192.168.106.24\\Non-Mission\\development\\data_circle\\metis\\output-test-suite\\2019lka01\\event_description.json"
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      domapchef:
        pipeline: map-chef
        stage: stage-run-map-create
        ignore_for_scheduling: false
    stages:
      - stage-launch:
          jobs:
            job-launch:
              resources:
                - arcmap10-6
              tasks:
                - *task_launch
                # - *extract_maps
