format_version: 9
common:
  task_create_pipeline: &task_create_pipeline
    - exec:
        command: cmd
        arguments:
          - "/c"
          - "C:/py27arcgis106/ArcGIS10.6/python.exe"
          - "-m"
          - pip
          - install
          - git+https://github.com/andrewphilipsmith/gocdapi.git
    - exec:
        command: cmd
        arguments:
          - "/c"
          - "C:/py27arcgis106/ArcGIS10.6/python.exe"
          - "pipelines/create_new_country_pipeline.py"
pipelines:
  map-chef-new-event-pipeline:
    group: Map-Creation-Group
    display_order: -2
    environment_variables:
      MAPCHEF_EVENT_DESC_PATH: "NOT_SET"
      py: "env\\Scripts\\python.exe"
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      mappipelines:
        type: configrepo
        destination: pipelines
    stages:
      - stage-create-pipeline:
          jobs:
            job-create-pipeline:
              resources:
                - arcmap10-6
                - hqfileserver
                - mapchef
              tasks:
                - *task_create_pipeline
