format_version: 9
common:
  task_venv: &task_venv
    - exec:
        command: cmd
        arguments:
          - "/c"
          - "C:/py27arcgis106/ArcGIS10.6/python.exe"
          - "-m"
          - virtualenv
          - "--system-site-packages"
          - env

  install_stable: &install_stable
    - exec:
        command: "env/Scripts/python.exe"
        arguments:
          - "-m"
          - pip
          - install
          - mapactionpy-controller
    - exec:
        command: "env/Scripts/python.exe"
        arguments:
          - "-m"
          - pip
          - install
          - mapactionpy-arcmap==0.7.dev171

  make_map: &make_map
    - exec:
        command: "env/Scripts/python.exe"
        arguments:
          - "-m"
          - mapactionpy_controller.check_naming_convention
          - "%cmf_description_path%"
    - exec:
        command: "env/Scripts/python.exe"
        arguments:
          - "-m"
          - mapactionpy_arcmap.arcmap_runner 
          - "--cmf"
          - "%cmf_path%"
          - "--product"
          - "Country Overview with Admin 1 Boundaries & P-Codes"

  extract_maps: &extract_maps
    - exec:
        command: "robocopy"
        arguments:
          - "%cmf_path%\\GIS\\3_Mapping\\34_Map_Products_MapAction"
          - outputmaps
          - "/mir"
          - "/NP"
          - "*.jpg"



pipelines:
  deployment-maps:
    group: Map-Creation-Group
    environment_variables:
      cmf_description_path: "\\\\192.168.106.24\\Crash-Move-Folder\\india\\2019dji01-for-testing-automation-tools\\cmf_description.json"
      cmf_path: "\\\\192.168.106.24\\Crash-Move-Folder\\india\\2019dji01-for-testing-automation-tools"
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      mappipelines:
        type: configrepo
        destination: configyaml
    stages:
      - stage-run-map-create:
          jobs:
            job-run-map-create:
              resources:
                - arcmap10-6
              artifacts:
                - build:
                    source: outputmaps
                    destination: maps
              tasks:
                - *task_venv
                - *install_stable
                - *make_map
                - *extract_maps

  test-maps-dji:
    group: Integration-Testing-Map-Group
    environment_variables:
      cmf_description_path: "\\\\192.168.106.24\\Crash-Move-Folder\\india\\2019dji01-for-testing-automation-tools\\cmf_description.json"
      cmf_path: "\\\\192.168.106.24\\Crash-Move-Folder\\india\\2019dji01-for-testing-automation-tools"
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    materials:
      mappipelines:
        type: configrepo
        destination: configyaml
      mapy-controller:
        scm: 7b37b961-6310-45e4-9968-25a17397b6a3
        destination: mapy-controller
      mapy-arcmap:
        scm: 8d4486df-9f5c-47fe-963e-ebd6ae376f83
        destination: mapy-arcmap
    stages:
      - stage-run-map-create:
          jobs:
            job-run-map-create:
              resources:
                - arcmap10-6
              artifacts:
                - build:
                    source: outputmaps
                    destination: maps
              tasks:
                - *task_venv
                - exec:
                    command: "env/Scripts/python.exe"
                    arguments:
                    - "-m"
                    - pip
                    - install
                    - "-e"
                    - mapy-controller
                - exec:
                    command: "env/Scripts/python.exe"
                    arguments:
                    - "-m"
                    - pip
                    - install
                    - "-e"
                    - mapy-arcmap
                - *make_map
                - *extract_maps


